version: "2"

services:
  www:
    build: .
    ports:
      - "8001:80"
    volumes:
      - ./www:/var/www/html/
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8002:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: db
    networks:
      - default

  db:
    image: mysql:5.5
    ports:
      - "8003:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: db
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    networks:
      default:
        aliases:
          - db

volumes:
  mysql-data:
